### ISSUE TITLE
Original Fields

### ISSUE THREAD

**Issue by idevelopr** [ZingyTomato/GaanaPy#4]
**Song length**: If possible, can you provide song length in seconds, please? I see Gaana is returning it in seconds.

**ScoreF**: When searching for songs, Gaana is retuning a field called ScoreF. It appears like the song with the highest _ScoreF_ is the most popular song.  Can you add _ScoreF_ to your API, please?

**Comment by ZingyTomato** [comment]
![image](https://user-images.githubusercontent.com/79736973/178653025-65c948cc-093a-4665-9802-e0085d3dd30a.png)

Seems that `hf` also determines whether it is the most popular.

**Comment by ZingyTomato** [comment]
@idevelopr I can't add `ScoreF` specifically because that is only available through gaana's search api endpoint. This api just uses the search api endpoint to get the track's `seokeys` and seokeys only. Nevertheless, the `songDetail` endpoint seems to return this.
![image](https://user-images.githubusercontent.com/79736973/178655237-e13a8a2c-17f4-41c6-b5a4-f47d743e8dc2.png)

**Comment by idevelopr** [comment]
Sounds reasonable. Yes, please add `popularity`
